import { analyzeRobustness, createCameraDetector, decodeInWorker, encode, reveal, type CameraDetector } from '../src/index.ts';
const el=<T extends HTMLElement>(id:string)=>document.querySelector<T>(`#${id}`)!;
const source=el<HTMLInputElement>('source'),payload=el<HTMLInputElement>('payload'),strength=el<HTMLInputElement>('strength'),detectFile=el<HTMLInputElement>('detectFile');
const encodeResult=el<HTMLPreElement>('encodeResult'),decodeResult=el<HTMLPreElement>('decodeResult'),encoded=el<HTMLDivElement>('encoded'),revealed=el<HTMLDivElement>('revealed');
el<HTMLButtonElement>('encode').onclick=async()=>{const file=source.files?.[0];if(!file)return alert('이미지를 선택하세요.');encodeResult.textContent='처리 중…';try{const result=await encode(file,{payload:payload.value,strength:Number(strength.value),outputType:'image/png'});const url=URL.createObjectURL(result.blob),image=new Image(),link=document.createElement('a');image.src=url;image.alt='Watermarked image';link.href=url;link.download='freqmark-watermarked.png';link.className='download';link.textContent='결과 저장';encoded.replaceChildren(image,document.createElement('br'),link);encodeResult.textContent=JSON.stringify({...result,blob:`[Blob ${result.blob.size} bytes]`},null,2)}catch(error){encodeResult.textContent=String(error)}};
el<HTMLButtonElement>('decode').onclick=async(event)=>{const file=detectFile.files?.[0];if(!file)return alert('이미지를 선택하세요.');const button=event.currentTarget as HTMLButtonElement;button.disabled=true;decodeResult.textContent='Worker에서 robust decode 중… 변형이 크거나 워터마크가 없으면 시간이 걸릴 수 있습니다.';try{decodeResult.textContent=JSON.stringify(await decodeInWorker(file,{robust:true}),null,2)}catch(error){decodeResult.textContent=`Decode 실패: ${String(error)}`}finally{button.disabled=false}};
el<HTMLButtonElement>('reveal').onclick=async()=>{const file=detectFile.files?.[0];if(!file)return alert('이미지를 선택하세요.');try{const result=await reveal(file,{robust:true,boost:7}),image=new Image();image.src=URL.createObjectURL(result.blob);image.alt='Revealed signal';revealed.replaceChildren(image);decodeResult.textContent=JSON.stringify(result.detection,null,2)}catch(error){decodeResult.textContent=String(error)}};
let camera:CameraDetector|null=null;el<HTMLButtonElement>('cameraStart').onclick=async()=>{const output=el<HTMLPreElement>('cameraResult');try{camera=createCameraDetector({video:el<HTMLVideoElement>('cameraVideo'),scanIntervalMs:200,resolution:720,searchRotation:true});camera.onResult(result=>{output.textContent=JSON.stringify({label:result.label,fingerprint:result.fingerprint,confidence:result.confidence,sync:result.sync},null,2)});await camera.start()}catch(error){output.textContent=String(error)}};el<HTMLButtonElement>('cameraStop').onclick=()=>{camera?.stop();camera=null};
el<HTMLButtonElement>('benchmark').onclick=async()=>{const file=source.files?.[0];if(!file)return alert('Encode 이미지를 선택하세요.');const output=el<HTMLPreElement>('benchmarkResult');output.textContent='Benchmark 실행 중…';try{output.textContent=JSON.stringify(await analyzeRobustness(file,{payload:payload.value,strength:Number(strength.value)}),null,2)}catch(error){output.textContent=String(error)}};
